cagov/design-system

.github/ISSUE_TEMPLATE/component-01-initial-proposal.md
.github/ISSUE_TEMPLATE/component-02-review-ux.md
.github/ISSUE_TEMPLATE/component-03-review-technical.md
.github/ISSUE_TEMPLATE/component-04-metadata.md
.github/ISSUE_TEMPLATE/component-05-publishing.md

Revise and split apart comprehensive issue template into phases, based on feedback from the team. The initial proposal can be generated by anyone. Then select components will enter a UX review, then a technical review. When a component is ready for building, it will get a metadata recommendation which will help developers to decide on a name & register the new component in the appropriate location. Finally, after development is complete (and the likely addition of a QA step), a review of the documentation, publishing and support can be completed.

Revise and split apart comprehensive issue template into phases

---

components/menu/package-lock.json
components/menu/package.json
components/menu/src/_style.scss

This fix adds back outline on focus state which was disabled. Caanbis.ca.gov issue #321

Fixed focus state in main menu

---

components/statewide-header/package-lock.json
components/statewide-header/package.json
components/statewide-header/readme.md
components/statewide-header/src/style.scss
components/statewide-header/template.html

This makes tagline that currently display "Official website of the State of California" tagline to show only "State of California" in mobile.

updated statewide-header component to v1.0.1 #67

---

components/content-navigation/package.json
components/content-navigation/src/index.scss

Reorganized sass file. Added border bottom to all list items and border top to the first child only. (Request came from https://github.com/cagov/cannabis.ca.gov/issues/223
Implemented solution is here: https://dev-cagov-dcc.pantheonsite.io/applicants/how-to-apply-renew/

Reorganized sass file. Added border bottom 

---

components/pdf-icon/CHANGELOG.md
components/pdf-icon/index.css
components/pdf-icon/index.css.map
components/pdf-icon/package-lock.json
components/pdf-icon/package.json
components/pdf-icon/pdf-link-example.html
components/pdf-icon/readme.md
components/pdf-icon/src/index.js
components/pdf-icon/src/index.scss

This one related to issue https://github.com/cagov/design-system/issues/113 and https://github.com/cagov/cannabis.ca.gov/issues/74

added pdf-icon component 

---

components/table/README.md
components/table/dist/index.css
components/table/dist/index.css.map
components/table/dist/index.wordpress.css
components/table/dist/index.wordpress.css.map
components/table/package-lock.json
components/table/package.json
components/table/src/index.scss
components/table/src/index.wordpress.scss
components/table/src/sass/_base.scss
components/table/src/template.html
components/table/test/test.config.js
components/table/test/test.index.js

- I'm not sure if this is the best way to handle wordpress vs headless. Open to ideas.
- Related PR: https://github.com/cagov/cannabis.ca.gov/pull/396

#143 Table component.

---

components/branding/CHANGELOG.md
components/branding/index.css
components/branding/package-lock.json
components/branding/package.json
components/branding/src/index.scss

Currently search bar border and search bar button background are using secondary color. Change it to the primary.

Changed search bar border and search button to Primary color #166

---

components/page-alert/package-lock.json
components/page-alert/package.json
components/page-alert/src/index.js
components/page-alert/test/index.test.js
unit-tests.md

This is a unit test document that came out of tri programming session with @kkoryaka and @xjensen 
Also ran into a few lint issues when I tried to commit so grouped those in this PR

Unit test docs

---

components/combined-css/dist/cagov.css
components/combined-css/dist/cannabis.css
components/combined-css/dist/drought.css
docs/pages/pages.11tydata.js
docs/pages/style/style.11tydata.js

Pages in subfolders are currently unavailable. That's bad! This fix resolves that problem while also removing a redundant data file. Win, win.

Fix nested permalinks

---

docs/site/_includes/branding.njk

Change site name to "Design System (beta)" as discussed this morning.

Change site name

---

docs/pages/principles.md
docs/site/_includes/layouts/component-index.njk
docs/site/_includes/layouts/landing.njk
docs/site/_includes/layouts/page.njk
docs/site/_includes/layouts/single-column.njk
docs/site/_includes/macros/principles-page-item.njk
docs/src/css/sass/ds-site-global.scss
docs/src/css/sass/index.scss
docs/src/css/sass/principles-page.scss

Modifies the principles page to more closely match our Figma mock-ups. Open to comment.

Improve principles layout

---

docs/src/js/component-sidebar.js

This is a quick fix to component page menu JS.

Fix component menu JS

---

docs/pages/get-started.md

updating-get-started

---

docs/pages/style/engineering.md
docs/site/_includes/menu.njk
docs/site/homepage.njk
docs/src/css/sass/feature-card-variations.scss
docs/src/css/sass/grids.scss

Iterative improvements to homepage styles. Getting into the small stuff.

Homepage style improvements

---

components/combined-css/CHANGELOG.md
components/combined-css/dist/index.js
components/menu/CHANGELOG.md
components/menu/package-lock.json
components/menu/package.json
components/menu/readme.md
components/menu/src/index.js

- Fixed aria-expanded attribute toggle issue on mobile search button click. 
- Added aria-controls attribute to the mobile search button.
- Added id (that is referenced by aria-controls attr) to the mobile search container.
- Added on resize mobile search reset function (it dis-activates mobile search on resize)
- Added mobile view function that determines if it is mobile view, which allows events happen only in mobile view.

Fixed mobile search accessibility issues and some bugs on window resize (#329)

---

components/base-css/src/_page.scss

* Add missing css class
* Please let me know when this is available in future version of the design system.

Single column wide css

---

docs/site/_includes/menu.njk

Two menu changes in this PR.
* Change the link label for the About page, per #377.
* Change order of menu items, per #376.

Change menu items

---

docs/src/css/sass/feature-card-variations.scss

This PR is one possible solution to the full-width form response jumping problem.

Change flex wrapping of homepage form

---

components/back-to-top/readme.md

- Updates to the last paragraph of back to top component description, thank you @zakiya 
- Change the demo/preview section to only be plain sample markup
- Add paragraph in the demo section saying the component is in the bottom right

update description and demo for back to top

---

.github/ISSUE_TEMPLATE/01-bug.md

This might be more appropriate for website projects than the design system but I think formal reports would be helpful. Devs, what do you think of using whatsmybrowser.org? I've found it helpful in the past.

Add to bug report template.

---

.github/ISSUE_TEMPLATE/03-task.md

Removing template language. (We need to think through our actual template, this is a patch to remove the word template until we can agree on our templates.

Remove template language

---

.github/ISSUE_TEMPLATE/design-system-01-proposal.md
.github/ISSUE_TEMPLATE/design-system-02-review-ux.md
.github/ISSUE_TEMPLATE/design-system-03-review-technical.md
.github/ISSUE_TEMPLATE/design-system-04-registration.md
docs/src/css/sass/feature-card-variations.scss
docs/src/js/airtable-form/src/cagov-airtable.form.js
docs/src/js/airtable-form/src/index.js
package-lock.json

Adjust some form styles that were creating white-on-white and blue-on-blue text.

2021 01 24 contact us styles

---

.github/ISSUE_TEMPLATE/design-system-01-proposal.md
.github/ISSUE_TEMPLATE/design-system-02-review-ux.md
.github/ISSUE_TEMPLATE/design-system-03-review-technical.md
.github/ISSUE_TEMPLATE/design-system-04-registration.md

Add Design System ## as a label in the issue template name so it's more clear they are for the design system process and can be ignored by newcomers.

Prefix label for design system process templates

---

docs/site/_includes/macros/design-system-form.njk
docs/src/css/sass/feature-card-variations.scss
docs/src/js/airtable-form/src/cagov-airtable.form.js
docs/src/js/airtable-form/src/index.js

Make it impossible to re-submit the form while server request is happening

2021 01 24 contact us throttling

---

components/agency-footer/readme.md
components/agency-footer/template.html

Fixes the oversized mail icon in the site footer demo.
Closes #418, #430.

Fix mail icon in site footer demo

---

docs/site/homepage.njk

Added sr-only text to two visit website links #535

---

.github/workflows/deploy-aws-staging.yml
.github/workflows/deploy-aws.yml
.github/workflows/pr-previews.yml
docs/site/_data/sitemap.json
docs/site/sitemap.njk

Adds a `sitemap.xml` file to the site.
Also adds a `robots.txt` file to the live site, and fixes it on the staging/preview sites.
Closes #433.

Add sitemap

---

docs/site/homepage.njk

Updated spacing by using utility classes @kmbrlygl  please review

updated homepage spacings #534

---

docs/site/_includes/agency-footer.njk
docs/site/_includes/macros/design-system-form.njk
docs/site/_includes/statewide-footer.njk

There was a note in Github about maybe adding other.
Jared also left a comment in the contact form mentioning that it's a good idea to include other. 
Submitting to staging, but we may need an agreement from whoever the comms/support team is.

2021 01 24 add other contact form

---

docs/site/_includes/agency-footer.njk

Per #287, add Google Analytics tracking to the site.
This gets us basic page views. We still need to discuss further event tracking, if needed.

Add Google Analytics

---

README.md

Issue: https://github.com/cagov/design-system/issues/586
Great collaboration writing this quickly together

adding readme content written by team

---

docs/site/homepage.njk
docs/src/css/sass/feature-card-variations.scss

Fixes scaling of the vector bear on the homepage.
Closes #451.

Fix scaling of the bear

---

docs/pages/style/design.md

Updating font size documentation to include rems sizing for desktop and mobile to better match what Konstantin said is in the CSS

Update font size documentation

---

docs/site/_includes/macros/design-system-form.njk

* #574 contact us changes
* Merge content changes from production (Verified as OK with content team - they are not pushing to staging)

574 contact us form

---

docs/site/_includes/layouts/component-index.njk
docs/src/css/sass/layout.scss
package-lock.json

This PR addresses #644, a QA item for the `1.0.1-rc-post-launch-fixes` release. 
@aaronhans Your call if we want to merge this now, or put it into the next sprint.

Fix Changelog layout

---

docs/site/_includes/statewide-header.njk

fixed statewide header structure #639

---

docs/site/error.njk

This PR makes several changes to the 404 page, notably removing the duplicate title.
Closes #675.

Fix 404 page

---

docs/site/_data/editable/principles.json

Opening PR to main for broken link fix

fix broken link to page feedback

---

components/step-list/src/index.scss

Remove declaration of Public Sans so that font setting can be adjusted globally as needed.
#708

Update padding on first step list number.

---

.eleventy.js
components/base-css/preview.md
test/index.spec.mjs

Fixes issues raised in https://github.com/cagov/design-system/issues/652
- Some filenames needed to be updated so they could be retrieved which resolved js errors
- The token display was removed because that is better handled in our design tokens section
- A new playwright test was added to review theme switcher to catch future regression

fix bugs on base css preview and add e2e test

---

components/icons/scripts/generateLibrary.js
components/icons/scripts/vars.js
docs/site/_includes/layouts/icon-library.njk

**QA link:**
[https://757-download-links.pr.designsystem.webstandards.ca.gov/pr/757-download-links/components/icons/readme/](https://757-download-links.pr.designsystem.webstandards.ca.gov/pr/757-download-links/components/icons/readme/)

757 - Icons - Remove "Download" from library links

---

CHANGELOG.md

Final changelog for release/1.0.4-equinox

Updated changelog for release/1.0.4-equinox

---

docs/pages/style/content.md
docs/pages/style/content/be-concise.md
docs/pages/style/content/build-accessibility-from-start.md
docs/pages/style/content/focus-on-user-needs-services.md
docs/pages/style/content/meet-your-audience-where-they-are.md
docs/pages/style/content/organize-content-strategically.md
docs/pages/style/content/write-in-plain-language.md
docs/pages/style/content/write-with-conversational-official-voice.md
docs/site/_includes/macros/component-card-list.njk
docs/site/homepage.njk
docs/src/css/sass/component-page.scss
package-lock.json

**4 Types of Cards Changed**
- Component Cards *(Put <a> tag around it with href)*
- Homepage "What's in the Design System" Cards *(Put <a> tag around it with href)*
- Homepage "Principles for people-centered digital services" Card *(Replaced <div> with <a> tag with href and classes)*
- Homepage "Who Using it" *(Replaced <div> with <a> tag with href and classes)*
Re: Issue 764

Links added to images in 4 types of cards

---

components/skip-to-content/README.md

I think this is a little clearer.

789 - Skip to content - Clarify instructions in readme.

---

README.md

Adding documentation to address: https://github.com/cagov/design-system/issues/776 and https://github.com/cagov/design-system/issues/775

add new sections to readme with more info on tests, directory structure

---

components/page-alert/package-lock.json

Reverts cagov/design-system#860

Revert "Bump minimist from 1.2.5 to 1.2.6 in /components/page-alert"

---

docs/site/homepage.njk
docs/src/css/sass/index.scss
docs/src/css/sass/page-alert.scss

Flex alert

---

docs/pages/style/content/write-with-conversational-official-voice.md

Added copy under the "how to sound official" section about the Immersive Reader tool.

Immersive-reader-update

---

.github/workflows/pr-previews.yml
package-lock.json
package.json

- Updated 11ty to v2, used https://github.com/11ty/eleventy-upgrade-help
- ran npm audit fix to address security vulnerabilities

11ty v2 package updates

---

docs/site/_includes/macros/design-system-form.njk

Need to merge this endpoint update too.
This is part of the planned updates to next release in the target branch. I thought I had already merged this in

use the new AWS hosted production endpoint for this form

---

.github/workflows/deploy-aws-staging.yml
.github/workflows/deploy-aws.yml
.github/workflows/pr-previews.yml
.github/workflows/validate.yml

This PR is only to test the new, more restrictive secrets applied to this repo. It includes no user facing changes.
If the build and deploy steps still work the increased security has been successful

minor git actions updates to test new strict secrets

---

docs/pages/why-web-components.md

- Fix 'bigOjbect' typo in why-web-components.md

Fix typo in markdown

---

components/icons/LICENSE
docs/site/_includes/site-footer.njk

Addresses issues: 
* #973
* #974
Regarding the GA4 statewide tracking code, I'm not sure if I got our "individual agency ID" correct (`G-PJDVH1C2JS`). Who can confirm this detail?

July 2023 updates

---

components/site-navigation/CHANGELOG.md
components/site-navigation/dist/index.js
components/site-navigation/package.json
components/site-navigation/src/index.js
package.json

Fixes Android search issue described in [#977](https://github.com/cagov/design-system/issues/977).
Note: I don't frequently modify this repo.  I am assuming the file changes I've made are sufficient (changelog, version number in package.json, and /src/ and /dist/ versions of the file), and I don't need to do any extra steps.  Please review!

Fixing Android search bug, as described in #977.

---

.github/workflows/deploy-aws-staging.yml
.github/workflows/deploy-aws.yml
.github/workflows/pr-previews.yml
.github/workflows/validate.yml

Updating from Node 16 -> 21 (latest within that major version number).  This is part of an ongoing effort to debug an issue with the PR preview feature.

Updated workflows to Node 21.

---

components/site-navigation/src/index.js

fix for google translate

---

components/page-navigation/package.json

Remove unneeded commands from prepublishOnly script

Modify prepublishOnly script
