cagov/design-system

components/google-translate/index.js, components/google-translate/package.json, components/google-translate/readme.md
New web component created to load the google translate widget but in a delayed fashion
- Load the component immediately if it had been clicked before
- If the component had not been loaded present a link to "change language"
- Keep track if the component had been clicked with a sessionStorage variable
=> add new module for google translate widget

components/statewide-header/CHANGELOG.md, components/statewide-header/index.css, components/statewide-header/package-lock.json, components/statewide-header/package.json, components/statewide-header/readme.md, components/statewide-header/src/index.scss, components/statewide-header/template.html
Per #120, this is a simple fix within ds-statewide-header to rename `.ofiicial-logo` to `.official-logo`.
I'll put in a separate PR to make the corresponding markup change in the headless.cannabis.ca.gov project.
This is my first PR to design-system, so let me know if I've missed any process or changes.
=> Rename ofiicial-logo to official-logo

components/content-navigation/CHANGELOG.md, components/content-navigation/package.json, components/content-navigation/src/index.scss
This will fix this bug:
https://github.com/cagov/cannabis.ca.gov/issues/394
=> removed sticky property since it is causing target scroll positioning issues

components/google-translate/index.js, components/google-translate/package-lock.json, components/google-translate/package.json, components/google-translate/preview.html
This PR updates the Google Translate component to 1.0.1, now linted and with a preview file.
=> Lint and update ds-google-translate to 1.0.1

components/statewide-footer/CHANGELOG.md, components/statewide-footer/index.css, components/statewide-footer/package-lock.json, components/statewide-footer/package.json, components/statewide-footer/src/index.scss
This issue came up in drought site (even though it looks good in cannabis). THis PR will fix it and make it consistent for all websites.
=> Added padding right 24px to the cagov-logo #162

components/content-navigation/CHANGELOG.md, components/content-navigation/package.json, components/content-navigation/src/index.scss
Currently content navigation border is using gray 200. Change it to Gray 300 (#e1e0e3)
=> changed content navigation's border color to gray-300 #165

components/combined-css/dist/cagov.css, components/combined-css/dist/cannabis.css, components/combined-css/dist/drought.css, components/external-link-icon/CHANGELOG.md, components/external-link-icon/index.css, components/external-link-icon/package-lock.json, components/external-link-icon/package.json, components/external-link-icon/src/index.scss
We recently discovered a problem with ds-external-link-icon in Firefox. The icons appear enormous.
The reason: Firefox will not honor a `min-width` or `max-width` that's applied to an **inline-block** element. This does not appear to be a Firefox bug; I think it's a deliberate decision on Mozilla's part. The fix for this is to just use a regular `width` instead. That's what's in this PR.
I've also changed the width's unit from `rem` to `em`, to help the icon grow and shrink with the size of the surrounding text.
=> Fix up width in ds-external-link-icon

components/combined-css/dist/cagov.css, components/combined-css/dist/cannabis.css, components/combined-css/dist/drought.css, components/feature-card/CHANGELOG.md, components/feature-card/package.json, components/feature-card/src/index.scss
This PR addresses a problem we discovered within ds-feature-card. The current h3 definition in that component resets h3 margins across the entire site. (If this is desired behavior, we should probably move this to ds-base-css.) 
This fix limits that h3 rule to just ds-feature-card.
=> Fix h3 reset in ds-feature-card

components/components.11tydata.js
Throughout our component markdown files, some filenames are capitalized and some are lower-cased. This doesn't matter with local builds, but it's breaking some links on S3/Cloudfront. This fix will ensure all component documents will be available at lower-cased URLs.
We can remove it if we rename all of our component documents into a consistent standard.
=> Fix component permalinks

docs/pages/principles.md, docs/site/_data/principles.json, docs/site/_includes/macros/principles-page-item.njk, docs/site/homepage.njk, docs/src/css/sass/ds-site-global.scss
This PR moves content regarding our principles into a data file, from which we can build the principles page AND fill in the featured principle card on the homepage.
The featured principle card on the homepage is currently random. It will refresh with each site build. 
Might be good to get some design input for the principles page. It feels special enough that we should dress it up a bit.
=> Build principles from data

components/accordion/README.md, docs/src/11ty/markdown.js, docs/src/css/sass/component-page.scss, docs/src/js/index.js
This PR improves the markdown code previews in a few ways.
* Adds a language label above the code block.
* Hopefully clarifies what's happening in the previews by enclosing it in a box with the relevant code snippet, at least a little.
* Code is better organized and documented.
Open to suggestion here.
=> Improve code blocks

components/accordion/CHANGELOG.md, components/accordion/README.md, components/accordion/package.json, components/base-css/preview.html, docs/src/publish/dynamic-html.js
This is an example of a process to keep the HTML samples in the readmes in synch with the HTML used when this component is tested. Please suggest improvements.
- Adds prepublish hook that runs new script
- Adds preset tag to readme around sample html so it can be retrieved
- Script gets latest HTML from template.html and writes it into the readme in the desired location
- readme.md and template.html filename values are hardcoded in script (not optimal)
Discussed this with @xjensen a bit and running the script at this point seems good because it will ensure browsable docs on npm get updated. The format: html preview is used after the markdown code delimiters because this is expected by the design system docs site and is used to display both a live preview using the HTML as well as a …
=> add dynamic html writing script to accordion

components/accordion/README.md, docs/src/publish/dynamic-html.js
This is a quick fix to ensure compatibility between markdown code previews on the site, and insert-html-into-readme-file script on the back end. 
I was running into this scenario where markdown was not rendering the code block. 
This happens because markdown really wants the code block delimiter (` ``` `) to be flush with the left margin of the document, no leading spaces. There should also be a new-line between the `<html-preview>` tags and the code-block delimiters. With these changes, everything looks fine, even if it leaves the code a bit uglier.
The other changes to the code all come from the linter.
=> Fix load-code-block-from-file previews

docs/pages/style/design.md, docs/src/css/sass/design-guide-page.scss, docs/src/css/sass/index.scss, package-lock.json, package.json
- Bumped 11ty to v1.0 release
- New page: Visual design style guide based on (hacked together with table tags in markdown):
=> add visual design style guide page and 11ty 1.0

components/accordion/package-lock.json, components/accordion/package.json, docs/src/publish/cdn-deploy.js, package-lock.json, package.json
Added a script that publishes the dist folder of a component to the CDN at:
```
components/${packageName}/v${packageVersion}/dist/*
```
This called from the prePublish hook and will cancel the publish process if it fails
If this is acceptable we can use this process for other components until we reorganize into a more centralized operation
=> add cdn deploy publishing step

.eleventyignore
This PR fixes a severe bug I discovered in component page rendering. It wasn't happening. At all. I believe the culprit was our upgrade to 11ty 1.0. I fixed it by reconfiguring our `.eleventyignore` file.
=> Fix component pages

docs/src/11ty/development-stage-transform.js
This PR moves the development stage widget (on component pages) to below the first H1 tag. We can move it elsewhere later, but the content team thinks this is a better interim position for this content.
=> Move development stage box

.eleventyignore, README.md, components/readme.md
Readme defines file structure needed for cdn deploy and dynamic writes into readme scripts to work
=> add link to component readme

components/statewide-header/CHANGELOG.md, components/statewide-header/package-lock.json, components/statewide-header/package.json, components/statewide-header/readme.md, components/statewide-header/template.html
- Updated statewide header's template.html code and make sure that cagov logo is linked to ca.gov website.
- Made sure that link has title attribute describing the link.
- Made sure that svg icon inside of the cagov-logo has aria-hidden=”true” attribute, so it is hidden from assistive technologies.
=> updated a11y it statewide-header #335

docs/site/homepage.njk
This PR fixes principles content on the homepage.
I missed this when I moved around the data files yesterday.
=> Fix principles on homepage

docs/src/11ty/markdown.js, package-lock.json, package.json
This PR adds `id` attributes to every heading tag generated by markdown. This will enable anchor links to mid-page content.
=> Add anchors to markdown headers

docs/site/_includes/menu.njk
This PR removes the Support link from the main navigation menu.
=> Remove Support from nav menu

components/components.11tydata.js, docs/pages/components.md, docs/site/_data/editable/components.json, docs/site/_data/editable/defaults.json, docs/site/_data/eleventyComputed.js, docs/site/_data/title.js
This PR appends the site's name to every page title.
It also provides a means to edit page titles and descriptions for component pages, as discussed with Content Team.
=> Improve page titles

docs/site/homepage.njk, docs/src/css/sass/grids.scss, package-lock.json
Instead of using custom "cagov-section-highlight" use common "lead" class specified in base-css typography.scss. These typography styles are specified in figma also:
=> changed cagov-section-highlight class to lead to fix typography on e homepage #233

docs/site/_data/editable/components.json
Removes the "new" label from the site footer in the component sidebar menu.
Closes #478.
=> Remove "new" label from site footer

docs/src/11ty/markdown.js
Fixes the bizarre vertical header on the skip-to-content page by removing H1 headings from special markdown processing (which adds `id` to every heading for the purposes of mid-page anchor-linking).
Closes #432.
=> Remove H1s from special markdown processing

docs/src/css/sass/component-page.scss
Fixes disappearance of component SVG illustrations on the components page.
Closes #440, #447.
=> Restore component SVGs in Safari

components/agency-footer/CHANGELOG.md, components/agency-footer/CONTRIBUTORS.md, components/agency-footer/package.json
- Added contributors.md 
- I think we should remove test:visual since it's not as useful as preview is now.
=> Agency footer - CONTRIBUTORS and CHANGELOG

components/branding/readme.md, components/branding/template.html, docs/src/css/sass/component-page.scss
Fixes a problem where entering a query into the search box on the site-header demo would go to a 404 page.
I think we could do a lot more to improve this demo. And I think this demo, in particular, calls into question the wisdom behind automatically merging our test `template.html` mark-up into the `readme.md`. The needs of our test code diverge significantly from the needs of simple communication re: how to use a component. 
But this fix stops the bleeding, at least.
Closes #485.
=> Remove form action from site-header search example

docs/site/_includes/layouts/component-index.njk
Fixes an accessibility issue with the components sidebar menu on component pages. The sidebar menu will now be picked up by assistive devices as a secondary navigation element.
Closes #326.
=> Make component sidebar menu an accessible landmark

components/pagination/readme.md
This PR populates the missing content model in the pagination component readme.
I lifted the content that was previously under the "Data attributes" heading and used it to create the "Content model" section. This matches what we're doing on other data-attribute-heavy components, like back-to-top and page-feedback.
Closes #483.
=> Fill out content model for pagination

components/skip-to-content/readme.md
This PR revises the code demo on the skip-to-content component. The goal here is to help people understand what the component is, how it works, and how to implement it.
There's an argument to be made that the proposed demonstration here is too sight-biased, given what should be an accessibility demo. I buy that argument, and we should discuss a better way to do this if it's a concern. With that said, I think this is much better than the lorem ipsum content we had before, for demonstration purposes. 
Again, in this case, I think it's a huge liability to merge our test content from `template.html` into `readme.md`.
Closes #487.
=> Provide guided demo for skip-to-content

components/accordion/CHANGELOG.md
- Added explanation to this changelog which had older, higher version numbers because it referred to a different package name.
- Took the legacy rocket syntax out of the changelog page title
- Changed the package name reference to be a link to npm
The last two items can be done everywhere if we like these updates
=> update changelog, explain higher version numbers

components/regulatory-outline/CHANGELOG.md, components/regulatory-outline/CONTRIBUTORS.md, components/regulatory-outline/dist/index.css, components/regulatory-outline/dist/index.css.map, components/regulatory-outline/package.json, components/regulatory-outline/readme.md, components/regulatory-outline/src/index.scss, components/regulatory-outline/template.html
PR for #493:
- Keep psuedo elements from covering borders
- Decrease padding and margins so there's more readability on small screens
- Added Changelog and Contribitor files
- Removed test:visual script
- Shortened example text (some may prefer to have it even shorter but it's useful for development to show how it behaves when numbers get especially long. 
- Changed the readme text a bit because it was inaccurate/confusing. (cc @m-sullivan7 See [preview](493-regulatory-outline.pr.designsystem.webstandards.ca.gov.))
Note of interest: I was going to test this in drought and cannabis but it seems this component is not in use anywhere. I think the original ask was from cannabis? cc: @chachasikes
=> 493 regulatory outline

docs/site/error.njk
Adds a 404 Not Found page, per #479.
Note that this requires an additional set-up step in our S3 bucket's "Static website hosting" properties. The error page needs to be set to "error.html". Already done for production.
Also note that this won't work for our special PR site set-up. If we want to use the error page within a given branch, we'd need to put some additional work to handle 404s into our Lambda@Edge Cloundfront stuff. Seems very low priority.
=> Add 404 page

docs/pages/contact-us.md
Removes content navigation from the Contact Us page.
Closes #510.
=> Remove content navigation from contact us page

docs/site/_includes/agency-footer.njk
A PR to avoid the following situation.
We have a discussion about this in #479. Some sort of feedback might be valuable here, but the particular contrast in wording between the error page and the feedback widget seems off here.
=> Remove feedback from error page

components/content-navigation/src/index.js, docs/pages/contact-us.md, docs/site/_includes/macros/contact-us-form-wrapper.njk, docs/site/_includes/macros/design-system-form.njk, docs/site/homepage.njk, docs/src/css/sass/feature-card-variations.scss
* Change form fields to match updated spec Issue: Update contact us form fields. Simplify form. #574
* Fix mysterious issue with select box after noticing two selects on contact us page form.
* Rename CSS class for contact us form to "contact-us" instead of "get-involved"
=> 574 contact form update

docs/src/css/sass/feature-card-variations.scss
Applies rounded borders to cards in the "What's in the Design System" section on the homepage.
Closes #503.
=> Apply rounded borders to stack card

docs/site/_data/eleventyComputed.js
Fixes the title on the homepage.
Titles on the site are appended with the site name. For example, if the article's title is "About", then "About | California Design System" is what appears in the `<title>` element.
However, on the homepage, the page title is the same as the site name. So you get "California Design System | California Design System".
This PR adds a check to ensure the page title and site name are not the same, before appending the site name.
=> Fix homepage title

components/page-alert/readme.md, docs/src/11ty/markdown.js, docs/src/css/sass/component-page.scss, docs/src/js/cagov-code-preview.js, docs/src/js/index.js
This PR adds an optional "Reset" button to code demos. This allows the reader to reset demos to an original state.
In particular, we need this for the page-alert demo, which disappears when closed. The reset button lets us bring that demo back after closing it.
This can be enabled in markdown by adding a `reset` instruction to the code block. For example:
````markdown
```html preview reset
<p>Demo here</p>
```
````
Closes #502.
=> Reset code demos

CHANGELOG.md, docs/src/css/sass/feature-card-variations.scss
This fixes a bug I introduced during the 1.0.1 release:
I made the header in the feature card on the homepage an H1 instead of an H2 because an H1 is required to pass accessibility audits. This created a design bug because the header was bigger.
Changing width of feature card width on desktop per @kmbrlygl's recommendation so the H1 has enough space to fit on 2 lines
=> make the title fit on two lines on desktop per design request

docs/src/js/cagov-code-preview.js
Fixes a style regression on the reset button for code demos.
This does change the color of the button from before. I imagine we'll be changing this again pending work on #662 and/or #627. But this feels fine for now.
Closes #502.
=> Fix button for code reset

docs/src/css/sass/component-page.scss
This PR fixes the a color contrast problem on the **Development stage** section of our component pages.
Closes #631
=> Fix color contrast of dev stage tracker

components/page-navigation/CHANGELOG.md, components/page-navigation/dist/index.js, components/page-navigation/package-lock.json, components/page-navigation/package.json, components/page-navigation/src/index.js
When clicking on a link in the page-navigation component, we expect the page to scroll to the linked section.  The browser's focus should also shift to the linked content. However, the latter is not happening. The focus stays inside the page-navigation component, even after the page scrolls to the desired section.
This is an accessibility problem for those who use keyboard navigation. They're unable to interact with the linked section of the page because the browser focus stays inside page-navigation.
This PR aims to fix that. 
Note: this new version of the page-navigation component will need to be published to npm upon merge into `main`.
Closes #661.
=> Fix page-navigation post-click focus

components/feature-card/CHANGELOG.md, components/feature-card/package.json, components/feature-card/readme.md, components/feature-card/template.html
Changes to sample markup:
- Do not use loading="lazy" because this is designed to be an above the fold image
- Use h1 instead of h2 for the header in the feature card because in all our use cases so far this has been appropriate and gets caught in axe accessibility audits
=> sample markup updates: h1 and no lazy loading

components/icons/CHANGELOG.md, components/icons/CONTRIBUTORS.md, components/icons/scripts/generateSprite.js, package-lock.json
- Some things i noticed when prepping to publish to npm.
=> 766 Icons 0.0.1

components/statewide-header/package-lock.json, components/statewide-header/package.json
We had bug fixes pushed in the last release for the statewide header component by outside contributors. Those updates took effect on the design system site because that site uses component source files in this repo.
The outside contributors won't have permission to republish our npm packages so I have done so
No code changes, just minor version bump the package and run the publish command which will
- Write updated files to our CDN at a version specific path
- Publish the latest version of the module to npm
The changelog already had info about the bugfix with this version number
=> Bump header

components/site-navigation/CHANGELOG.md, components/site-navigation/README.md, components/site-navigation/dist/index.js, components/site-navigation/package.json, components/site-navigation/src/index.js, components/site-navigation/template.html, components/site-navigation/test/index.js, components/statewide-header/package-lock.json, components/statewide-header/package.json, docs/site/_includes/site-navigation.njk
This change is a result of axe-accessibility checker flagging inappropriate use of aria-expanded when using the ds-site-navigation component on the digital.ca.gov site.
It looks like the expected use is to use that attribute on a button element that controls the expansion and collapse. I have added aria-controls to the button in the sample html to match ids on the expanding sections
Referred to docs: https://www.w3.org/WAI/GL/wiki/Using_the_WAI-ARIA_aria-expanded_state_to_mark_expandable_and_collapsible_regions
=> A11y mav menu aria expanded

components/accordion/README.md, components/accordion/template.html
This change updates the accordion sample HTML so that it does not include buttons. This avoids providing a bad example because we probably don't want buttons be be inside accordions where they might be missed. Thank you @ashleydraper! Links provide the same focus example and are a better content example
=> updating accordion docs inside the design system without bumping version

docs/src/css/sass/component-page.scss, docs/src/js/component-sidebar.js
@xjensen 
https://github.com/cagov/design-system/issues/640
- Although the original issue said to use an 'X" icon, I was wondering if it would make more sense to use a up / down arrow animation (my PR has this up / down animation for reference)? The up / down arrow seems to be used already for drop downs when there is a full row present whereas the only time I see the "X" icon used in a dropdown is in the "Menu" where it goes from a hamburger icon to an "X". The "Menu" on the top right though is a button whereas the "Components" dropdown is a full row.
- If the "X" makes more sense, I was also wondering where I can find the "X" icon itself? It looks like the arrow is drawn using a  <path> tag but I couldn't find the equivalent for the "X". Also I was wondering if someone could explain how …
=> Simple arrow animation suggestion

components/page-navigation/CHANGELOG.md, components/page-navigation/dist/index.js, components/page-navigation/package.json, components/page-navigation/src/index.js, package-lock.json
Dynamically adds `tabindex="-1"` to headings via the page-navigation component. This fixes problems with anchor linking in the JAWS screen reader.
Fixes #931
=> Add tabindex to page-navigation

components/site-header/README.md, components/site-header/template.html
Addresses an issue (#821) with a link that navigated away from demo code in the site-header example.  Clicking on the cannabis logo now stays put.
=> Site header logo link removal

components/site-navigation/CHANGELOG.md, components/site-navigation/README.md, components/site-navigation/dist/index.js, components/site-navigation/package.json, components/site-navigation/src/index.js
This changes the strategy used to ignore needless resizes on Android phones. Instead of using a boolean flag to detect when the mobile search-icon was pressed, it detects when the window's innerWidth has changed, and if not, it does not reset the search elements.  Code is a bit simpler, and this will consistently work if multiple resize events are generated.
=> Version 3.0.2 of ds-site-navigation. See CHANGELOG.

components/pagination/CHANGELOG.md, components/pagination/dist/index.js, components/pagination/package.json, components/pagination/src/template.js
This fixes a display issue with pagination buttons.  The current code displays the following when there are 4 available pages.
Notice that on page 1, Page 3 is mysteriously dropped.    On Page 4, an ellipsis is displayed in place of a single page (ellipsis should only be used for 2 or more pages).
There are similar issues with 5 page, 6 page, and 7 page displays.  Here is a 7 page display.
Notice that an ellipsis is shown in place of a single page, and page 6 is missing.
This patch shows the ellipsis in cases where it represents 2 or more pages, and shows a single page in its place, when it is appropriate to do, fixing all the above issues.
=> Pagination display fix.  @cagov/ds-pagination version 2.0.4

.husky/pre-commit, components/base-css/test-config.js, docs/src/11ty/for-unset-components.js, package-lock.json, package.json, test/test.config.js
- Update ESLint from 7.32.0 to 8.57.0 (latest stable)
- Update Prettier from 2.4.1 to 3.3.3 (latest)
- Update Husky from 7.0.4 to 9.0.11 (latest)
- Update Glob from 7.2.0 to 10.3.10 (latest)
- Update Playwright from 1.25.1 to 1.48.2 (latest)
- Update Web Test Runner from 0.13.16 to 0.18.0 (latest)
- Update Web Dev Server from 0.1.17 to 0.2.0 (latest)
- Update Sharp from 0.32.6 to 0.33.5 (latest)
- Replace @web/test-runner-puppeteer with @web/test-runner-playwright to resolve ARM64 Chromium binary issues
- Update test configurations to use Playwright instead of Puppeteer
- Fix regex pattern in for-unset-components.js to handle paths without trailing slashes
- Fix Husky pre-commit hook configuration for v9 compatibility
- Resolve npm install failures by using --ignore-scripts flag
- Fix …
=> Update deprecated packages and resolve npm install issues
